### ISSUE TITLE
Java Track Courses to be Completed

### ISSUE THREAD

**Issue by FlyingHammer** [FlyingHammer/Treehouse#2]
## Todo
- Courses left to complete
- [x] Java Basics
- [ ] Java Objects
- [ ] Java Data Structures
- [ ] Local Development Environments
- [ ] Build a JavaFx Application

:+1: 
cc @gmckay
